train: # metrics that are calculated during training
  - _target_: src.metrics.BeamCERMetric
    name: "training_CER_(BeamSearch)"
    beam_size: 5
  - _target_: src.metrics.BeamWERMetric
    name: "training_WER_(BeamSearch)"
    beam_size: 5

inference: # metrics that are calculated during inference (eval)
  - _target_: src.metrics.BeamCERMetric
    name: "eval_CER_(BeamSearch)" # it is better to avoid spaces in names
    beam_size: 5
  - _target_: src.metrics.BeamWERMetric
    name: "eval_WER_(BeamSearch)"
    beam_size: 5
